import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
   variable: "--font-montserrat",
   subsets: ["latin"],
   weight: ["400", "500", "600", "700"],
});

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="fr">
         <body
            className={`${montserrat.variable} antialiased relative isolate after:content-[''] after:fixed after:top-0 after:left-0 after:w-full after:h-full after:bg-gradient-to-b after:from-background-light after:to-background after:-z-10`}
            suppressHydrationWarning={true}
         >
            <Header />
            <main className="min-h-screen">{children}</main>
            <Footer />
         </body>
      </html>
   );
}
